@include('admin.layouts.header')
<link rel="stylesheet" href="<?= URL_ROOT ?>/public/css/system-log.css?v=<?= filemtime(APP_ROOT.'/public/css/system-log.css') ?>">
<div class="container-fluid log-shell pb-4">
  <?php if(Session::get('system_log_msg')): ?><div class="alert alert-success"><?= htmlspecialchars(Session::get('system_log_msg'));Session::delete('system_log_msg'); ?></div><?php endif; ?>
  <div class="log-hero p-4 mb-4"><div class="d-flex flex-wrap justify-content-between align-items-center gap-3"><div><div class="small opacity-75">Audit Trail & Security Monitoring</div><h2 class="h4 fw-bold my-1">Nhật ký hệ thống</h2><div class="small opacity-75">Theo dõi hoạt động, đăng nhập, thao tác quản trị và lỗi ứng dụng.</div></div><a href="<?= URL_ROOT ?>/admin/system-log/error?resolved=0" class="btn btn-light btn-sm"><i class="fa-solid fa-triangle-exclamation me-1"></i><?= number_format($s['unresolved_errors']) ?> lỗi chưa xử lý</a></div></div>
  <?php $cards=[['activity_today','Activity hôm nay','fa-bolt','primary'],['login_today','Login','fa-right-to-bracket','success'],['admin_today','Admin Action','fa-user-shield','info'],['error_today','Error','fa-bug','danger'],['failed_today','Failed Login','fa-shield-halved','warning'],['unresolved_errors','Chưa xử lý','fa-circle-exclamation','danger']]; ?>
  <div class="row g-3 mb-4"><?php foreach($cards as [$key,$label,$icon,$color]): ?><div class="col-xl-2 col-md-4 col-6"><div class="card log-card h-100"><div class="card-body"><div class="d-flex align-items-center gap-3"><span class="log-stat-icon bg-<?= $color ?> bg-opacity-10 text-<?= $color ?>"><i class="fa-solid <?= $icon ?>"></i></span><div><div class="log-stat-value"><?= number_format($s[$key]) ?></div><div class="small text-muted fw-semibold"><?= $label ?></div></div></div></div></div></div><?php endforeach; ?></div>
  <div class="nav nav-pills log-tabs gap-2 mb-4"><a class="nav-link" href="<?= URL_ROOT ?>/admin/system-log/activity"><i class="fa-solid fa-list-check me-1"></i>Activity Log</a><a class="nav-link" href="<?= URL_ROOT ?>/admin/system-log/admin"><i class="fa-solid fa-user-shield me-1"></i>Admin Log</a><a class="nav-link" href="<?= URL_ROOT ?>/admin/system-log/login"><i class="fa-solid fa-right-to-bracket me-1"></i>Login History</a><a class="nav-link" href="<?= URL_ROOT ?>/admin/system-log/error"><i class="fa-solid fa-bug me-1"></i>Error Log</a></div>
  <div class="card log-card mb-4"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h6 class="fw-bold mb-0">Xu hướng hệ thống</h6><div class="btn-group btn-group-sm"><button type="button" class="btn btn-primary" data-log-chart-period="day">Theo ngày</button><button type="button" class="btn btn-outline-primary" data-log-chart-period="week">Theo tuần</button><button type="button" class="btn btn-outline-primary" data-log-chart-period="month">Theo tháng</button></div></div><div class="log-chart"><canvas id="systemLogChart"></canvas></div></div></div>
  <div class="row g-3 mb-4"><div class="col-lg-6"><div class="card log-card h-100"><div class="card-header bg-white border-0 fw-bold pt-3">Admin Action gần đây</div><div class="table-responsive"><table class="table table-sm mb-0"><tbody><?php foreach($l['recent_admin'] as $row): ?><tr><td class="ps-3"><span class="badge bg-primary-subtle text-primary"><?= htmlspecialchars($row->module) ?></span></td><td><?= htmlspecialchars($row->actor_name??'Hệ thống') ?><div class="small text-muted"><?= htmlspecialchars($row->action) ?></div></td><td class="text-end pe-3 small text-muted"><?= date('d/m H:i',strtotime($row->created_at)) ?></td></tr><?php endforeach; ?><?php if(!$l['recent_admin']): ?><tr><td class="text-center text-muted py-4">Chưa có dữ liệu</td></tr><?php endif; ?></tbody></table></div></div></div>
  <div class="col-lg-6"><div class="card log-card h-100"><div class="card-header bg-white border-0 fw-bold pt-3">Lỗi gần đây</div><div class="table-responsive"><table class="table table-sm mb-0"><tbody><?php foreach($l['recent_errors'] as $row): ?><tr><td class="ps-3"><span class="badge bg-danger-subtle text-danger"><?= htmlspecialchars($row->level) ?></span></td><td><div class="log-message"><?= htmlspecialchars($row->message) ?></div><small class="text-muted"><?= htmlspecialchars($row->module) ?></small></td><td class="text-end pe-3"><a href="<?= URL_ROOT ?>/admin/system-log/detail/<?= $row->id ?>?type=error" class="btn btn-sm btn-outline-secondary">Xem</a></td></tr><?php endforeach; ?><?php if(!$l['recent_errors']): ?><tr><td class="text-center text-muted py-4">Chưa có lỗi</td></tr><?php endif; ?></tbody></table></div></div></div></div>
  <div class="card log-card"><div class="card-body d-flex flex-wrap justify-content-between align-items-center gap-3"><div><h6 class="fw-bold mb-1">Chính sách lưu trữ</h6><div class="small text-muted">Xóa log cũ để kiểm soát dung lượng. Thao tác này không thể hoàn tác.</div></div><form method="POST" action="<?= URL_ROOT ?>/admin/system-log/purge" class="d-flex gap-2" onsubmit="return confirm('Bạn chắc chắn muốn xóa các log cũ?')"><?= Csrf::field() ?><select name="months" class="form-select form-select-sm"><option value="6">Cũ hơn 6 tháng</option><option value="12" selected>Cũ hơn 1 năm</option><option value="24">Cũ hơn 2 năm</option></select><button class="btn btn-outline-danger btn-sm text-nowrap"><i class="fa-solid fa-trash-can me-1"></i>Dọn log</button></form></div></div>
</div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script>window.SystemLogDashboardData=<?= json_encode($l['daily'],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;</script><script src="<?= URL_ROOT ?>/public/js/system-log-dashboard.js?v=<?= filemtime(APP_ROOT.'/public/js/system-log-dashboard.js') ?>"></script>
@include('admin.layouts.footer')
