@include('admin.layouts.header')
<link rel="stylesheet" href="<?= URL_ROOT ?>/public/css/system-log.css?v=<?= filemtime(APP_ROOT.'/public/css/system-log.css') ?>">
<div class="container-fluid log-shell pb-4">
  <div class="d-flex flex-wrap justify-content-between align-items-center gap-2 mb-3"><div><a href="<?= URL_ROOT ?>/admin/system-log" class="small text-decoration-none"><i class="fa-solid fa-arrow-left me-1"></i>Dashboard nhật ký</a><h2 class="h4 fw-bold mt-2 mb-0"><?= htmlspecialchars($title) ?></h2></div><a href="<?= URL_ROOT ?>/admin/system-log/export/<?= $type ?>?<?= http_build_query($_GET) ?>" class="btn btn-success btn-sm"><i class="fa-solid fa-file-csv me-1"></i>Xuất CSV</a></div>
  <div class="nav nav-pills log-tabs gap-2 mb-3"><?php foreach(['activity'=>'Activity','admin'=>'Admin','login'=>'Login','error'=>'Error'] as $key=>$label): ?><a class="nav-link <?= $type===$key?'active':'' ?>" href="<?= URL_ROOT ?>/admin/system-log/<?= $key ?>"><?= $label ?></a><?php endforeach; ?></div>
  <form method="GET" class="log-filter p-3 mb-3"><div class="row g-2 align-items-end">
    <div class="col-xl-3 col-md-6"><label class="form-label small fw-bold">Tìm kiếm</label><input name="q" value="<?= htmlspecialchars($f['q']) ?>" class="form-control form-control-sm" placeholder="Hành động, email, nội dung..."></div>
    <?php if($type!=='login'): ?><div class="col-xl-2 col-md-3"><label class="form-label small fw-bold">Module</label><select name="module" class="form-select form-select-sm"><option value="">Tất cả</option><?php foreach($l['modules'] as $module): ?><option value="<?= htmlspecialchars($module) ?>" <?= $f['module']===$module?'selected':'' ?>><?= htmlspecialchars($module) ?></option><?php endforeach; ?></select></div><?php endif; ?>
    <?php if(in_array($type,['activity','admin'],true)): ?><div class="col-xl-2 col-md-3"><label class="form-label small fw-bold">Hành động</label><input name="action" value="<?= htmlspecialchars($f['action']) ?>" class="form-control form-control-sm" placeholder="approve, update..."></div><?php endif; ?>
    <div class="col-xl-1 col-md-2"><label class="form-label small fw-bold"><?= $type==='admin'?'Admin ID':'User ID' ?></label><input type="number" min="1" name="user_id" value="<?= $f['user_id']?:'' ?>" class="form-control form-control-sm"></div>
    <?php if($type==='login'): ?><div class="col-xl-2 col-md-3"><label class="form-label small fw-bold">Trạng thái</label><select name="status" class="form-select form-select-sm"><option value="">Tất cả</option><?php foreach(['success'=>'Thành công','failed'=>'Thất bại','blocked'=>'Bị chặn','logout'=>'Đăng xuất'] as $key=>$label): ?><option value="<?= $key ?>" <?= $f['status']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><?php endif; ?>
    <?php if($type==='error'): ?><div class="col-xl-2 col-md-3"><label class="form-label small fw-bold">Mức độ</label><select name="level" class="form-select form-select-sm"><option value="">Tất cả</option><?php foreach(SystemLog::ERROR_LEVELS as $level): ?><option value="<?= $level ?>" <?= $f['level']===$level?'selected':'' ?>><?= ucfirst($level) ?></option><?php endforeach; ?></select></div><div class="col-xl-2 col-md-3"><label class="form-label small fw-bold">Xử lý</label><select name="resolved" class="form-select form-select-sm"><option value="">Tất cả</option><option value="0" <?= $f['resolved']==='0'?'selected':'' ?>>Chưa xử lý</option><option value="1" <?= $f['resolved']==='1'?'selected':'' ?>>Đã xử lý</option></select></div><?php endif; ?>
    <div class="col-xl-2 col-md-3"><label class="form-label small fw-bold">IP</label><input name="ip" value="<?= htmlspecialchars($f['ip']) ?>" class="form-control form-control-sm" placeholder="192.168..."></div>
    <div class="col-xl-2 col-md-3"><label class="form-label small fw-bold">Từ ngày</label><input type="date" name="from" value="<?= $f['from'] ?>" class="form-control form-control-sm"></div><div class="col-xl-2 col-md-3"><label class="form-label small fw-bold">Đến ngày</label><input type="date" name="to" value="<?= $f['to'] ?>" class="form-control form-control-sm"></div>
    <div class="col-xl-1 col-md-2"><label class="form-label small fw-bold">Số dòng</label><select name="per_page" class="form-select form-select-sm"><?php foreach([25,50,100] as $n): ?><option <?= $l['per_page']===$n?'selected':'' ?>><?= $n ?></option><?php endforeach; ?></select></div><div class="col-xl-1 col-md-2"><button class="btn btn-primary btn-sm w-100">Lọc</button></div><div class="col-xl-1 col-md-2"><a href="<?= URL_ROOT ?>/admin/system-log/<?= $type ?>" class="btn btn-outline-secondary btn-sm w-100">Xóa lọc</a></div>
  </div></form>
  <div class="card log-card"><div class="card-header bg-white border-0 pt-3 d-flex justify-content-between"><span class="fw-bold"><?= number_format($l['total']) ?> bản ghi</span><a href="?<?= http_build_query(array_merge($_GET,['order'=>$f['order']==='desc'?'asc':'desc'])) ?>" class="small text-decoration-none">Thời gian <i class="fa-solid fa-arrow-<?= $f['order']==='desc'?'down':'up' ?>"></i></a></div><div class="table-responsive"><table class="table table-hover log-table mb-0"><thead class="table-light"><tr>
    <th>Thời gian</th><?php if($type==='activity'): ?><th>Người dùng</th><th>Hành động</th><th>Đối tượng</th><th>IP / Thiết bị</th><?php elseif($type==='admin'): ?><th>Admin</th><th>Module / Hành động</th><th>Đối tượng</th><th>IP</th><?php elseif($type==='login'): ?><th>Tài khoản</th><th>Thiết bị</th><th>IP / Quốc gia</th><th>Trạng thái</th><?php else: ?><th>Module</th><th>Mức độ</th><th>Nội dung lỗi</th><th>Người dùng</th><th>Trạng thái</th><?php endif; ?><th></th></tr></thead><tbody>
    <?php if(!$l['rows']): ?><tr><td colspan="8" class="text-center text-muted py-5">Không có dữ liệu phù hợp.</td></tr><?php endif; ?>
    <?php foreach($l['rows'] as $row): ?><tr><td class="text-nowrap"><b><?= date('d/m/Y',strtotime($row->created_at)) ?></b><div class="small text-muted"><?= date('H:i:s',strtotime($row->created_at)) ?></div></td>
      <?php if($type==='activity'): ?><td><?= htmlspecialchars($row->actor_name??'Khách') ?><div class="small text-muted"><?= htmlspecialchars($row->actor_email??'') ?></div></td><td><span class="badge bg-primary-subtle text-primary"><?= htmlspecialchars($row->action) ?></span><div class="small mt-1"><?= htmlspecialchars($row->module) ?></div></td><td><?= htmlspecialchars($row->target_type??'—') ?> <?= $row->target_id?'#'.(int)$row->target_id:'' ?></td><td><?= htmlspecialchars($row->ip_address??'') ?><div class="small text-muted log-message" style="max-width:180px"><?= htmlspecialchars($row->user_agent??'') ?></div></td>
      <?php elseif($type==='admin'): ?><td><?= htmlspecialchars($row->actor_name??'Hệ thống') ?><div class="small text-muted"><?= htmlspecialchars($row->actor_email??'') ?></div></td><td><span class="badge bg-info-subtle text-info"><?= htmlspecialchars($row->module) ?></span><div class="small mt-1"><?= htmlspecialchars($row->action) ?></div></td><td><?= htmlspecialchars($row->target_type??'—') ?> <?= $row->target_id?'#'.(int)$row->target_id:'' ?></td><td><?= htmlspecialchars($row->ip_address??'') ?></td>
      <?php elseif($type==='login'): ?><td><?= htmlspecialchars($row->email??'—') ?><div class="small text-muted"><?= $row->user_id?'User #'.(int)$row->user_id:'Không xác định' ?></div></td><td><?= htmlspecialchars(($row->browser??'').' · '.($row->platform??'')) ?><div class="small text-muted"><?= htmlspecialchars($row->device??'') ?></div></td><td><?= htmlspecialchars($row->ip_address??'') ?><div class="small text-muted"><?= htmlspecialchars($row->country??'') ?></div></td><td><span class="badge bg-<?= $row->status==='success'?'success':($row->status==='logout'?'secondary':'danger') ?>"><?= htmlspecialchars($row->status) ?></span><div class="small text-danger mt-1"><?= htmlspecialchars($row->fail_reason??'') ?></div></td>
      <?php else: ?><td><span class="badge bg-secondary-subtle text-secondary"><?= htmlspecialchars($row->module) ?></span><div class="small text-muted"><?= htmlspecialchars($row->error_type??'') ?></div></td><td><span class="badge bg-<?= in_array($row->level,['error','critical'],true)?'danger':($row->level==='warning'?'warning':'info') ?>"><?= htmlspecialchars($row->level) ?></span></td><td><div class="log-message"><?= htmlspecialchars($row->message) ?></div><small class="text-muted"><?= htmlspecialchars($row->request_method.' '.$row->request_url) ?></small></td><td><?= htmlspecialchars($row->actor_name??'Hệ thống') ?></td><td><span class="badge bg-<?= $row->resolved?'success':'warning text-dark' ?>"><?= $row->resolved?'Đã xử lý':'Chưa xử lý' ?></span></td><?php endif; ?>
      <td class="text-end"><a href="<?= URL_ROOT ?>/admin/system-log/detail/<?= $row->id ?>?type=<?= $type ?>" class="btn btn-sm btn-outline-primary">Chi tiết</a></td></tr><?php endforeach; ?>
  </tbody></table></div></div>
  <?php if($l['total_pages']>1): ?><nav class="mt-3"><ul class="pagination pagination-sm justify-content-center"><?php for($p=1;$p<=$l['total_pages'];$p++): ?><li class="page-item <?= $p===$l['page']?'active':'' ?>"><a class="page-link" href="?<?= http_build_query(array_merge($_GET,['page'=>$p])) ?>"><?= $p ?></a></li><?php endfor; ?></ul></nav><?php endif; ?>
</div>@include('admin.layouts.footer')
