<link rel="stylesheet" href="<?= URL_ROOT ?>/public/css/gemini-chatbot.css?v=<?= filemtime(APP_ROOT.'/public/css/gemini-chatbot.css') ?>">
<button id="gcb-toggle" class="gcb-fab" type="button" aria-label="Mở trợ lý AI"><img src="<?= URL_ROOT ?>/public/images/chatbot/ai-robot-color.png" alt="Trợ lý AI"></button>
<section id="gcb-window" class="gcb-window" aria-hidden="true">
  <header><div><img class="gcb-avatar" src="<?= URL_ROOT ?>/public/images/chatbot/ai-robot-color.png" alt="Robot AI"><b>Trợ lý TimNhaDat AI</b><small><i></i> Đang trực tuyến</small></div><button id="gcb-close" aria-label="Đóng">&times;</button></header>
  <div id="gcb-messages" class="gcb-messages"></div>
  <div class="gcb-chips"><button data-q="Tôi muốn liên hệ tư vấn">Liên hệ tư vấn</button><button data-q="Cho tôi xem bảng giá">Xem bảng giá</button><button data-q="Tôi muốn tìm hiểu dịch vụ">Tìm hiểu dịch vụ</button></div>
  <footer><textarea id="gcb-input" rows="1" maxlength="2000" placeholder="Nhập câu hỏi..."></textarea><button id="gcb-send" disabled aria-label="Gửi"><i class="fa-solid fa-paper-plane"></i></button></footer>
</section>
<script>document.addEventListener('DOMContentLoaded',()=>{const W=document.querySelector('#gcb-window'),M=document.querySelector('#gcb-messages'),I=document.querySelector('#gcb-input'),S=document.querySelector('#gcb-send'),T=document.querySelector('#gcb-toggle');let H=[];try{H=JSON.parse(sessionStorage.getItem('tnd_gemini_chat')||'[]')}catch(e){}const esc=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));const md=s=>esc(s).replace(/\*\*(.*?)\*\*/g,'<strong>$1</strong>').replace(/\[(.*?)\]\(((?:https?:\/\/|\/)[^\s)]+)\)/g,'<a href="$2" target="_blank" rel="noopener">$1</a>').replace(/\n/g,'<br>');const bottom=()=>{M.scrollTop=M.scrollHeight};const add=(r,t,save=true)=>{let d=document.createElement('div');d.className='gcb-msg '+r;d.innerHTML=r==='model'?md(t):esc(t);M.appendChild(d);if(save){H.push({role:r,text:t});H=H.slice(-20);sessionStorage.setItem('tnd_gemini_chat',JSON.stringify(H))}bottom()};if(H.length)H.forEach(x=>add(x.role,x.text,false));else add('model','Xin chào! Mình có thể giúp bạn tìm hiểu dịch vụ và kết nối tư vấn viên.',false);const open=()=>{W.classList.add('open');W.setAttribute('aria-hidden','false');setTimeout(()=>{I.focus();bottom()},150)};T.onclick=open;document.querySelector('#gcb-close').onclick=()=>{W.classList.remove('open');W.setAttribute('aria-hidden','true')};I.oninput=()=>{I.style.height='auto';I.style.height=Math.min(I.scrollHeight,100)+'px';S.disabled=!I.value.trim()};I.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();send()}};document.querySelector('.gcb-chips').onclick=e=>{let b=e.target.closest('button');if(b){I.value=b.dataset.q;S.disabled=false;send()}};S.onclick=send;async function send(){let q=I.value.trim();if(!q)return;let context=H.slice(-12);add('user',q);I.value='';I.style.height='auto';S.disabled=true;let typing=document.createElement('div');typing.className='gcb-msg model typing';typing.innerHTML='<i></i><i></i><i></i>';M.appendChild(typing);bottom();try{let r=await fetch('<?= URL_ROOT ?>/chatbot/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:q,history:context,_csrf_token:'<?= Csrf::token() ?>'})});let d=await r.json();typing.remove();add('model',d.success&&d.reply?d.reply:(d.message||'Trợ lý đang bận, vui lòng thử lại.'))}catch(e){typing.remove();add('model','Kết nối đang gián đoạn. Bạn vui lòng thử lại sau nhé.')}}});</script>
