@include('layouts.header')
<?php $a=$data['analytics']; $post=$a['post']; $s=$a['summary']; $r=$a['range']; ?>
<link rel="stylesheet" href="<?= URL_ROOT ?>/public/css/analytics.css?v=<?= filemtime(APP_ROOT . '/public/css/analytics.css') ?>">
<div class="container py-4 analytics-shell"><div class="row">
@include('nguoi-dung.sidebar')
<main class="col-lg-9 col-md-8">
  <div class="d-flex justify-content-between align-items-center mb-3"><div><a href="<?= URL_ROOT ?>/nguoi-dung/analytics" class="small text-decoration-none"><i class="fa-solid fa-arrow-left me-1"></i>Dashboard Analytics</a><h2 class="h4 fw-bold mt-2 mb-0">Chi tiết Analytics</h2></div><a href="<?= URL_ROOT ?>/du-an/detail/<?= urlencode($post->duong_dan) ?>" class="btn btn-outline-primary btn-sm" target="_blank">Xem tin</a></div>
  <div class="card analytics-card p-3 mb-4"><div class="d-flex flex-column flex-sm-row gap-3 align-items-sm-center"><img class="analytics-post-thumb" style="width:120px;height:86px" src="<?= htmlspecialchars(img_url((string)$post->anh_thu_nho)) ?>" alt=""><div class="flex-grow-1"><h5 class="fw-bold mb-2"><?= htmlspecialchars($post->tieu_de) ?></h5><div class="d-flex flex-wrap gap-2 small"><span class="badge bg-<?= $post->trang_thai==='xuat_ban'?'success':'secondary' ?>"><?= htmlspecialchars($post->trang_thai) ?></span><span class="badge bg-<?= (int)$post->goi_vip>0?'warning text-dark':'light text-dark border' ?>"><?= (int)$post->goi_vip>0?'VIP '.$post->goi_vip:'Tin thường' ?></span><span class="text-muted">Đăng <?= date('d/m/Y',strtotime($post->ngay_tao)) ?></span><?php if($post->ngay_het_han_vip): ?><span class="text-muted">Hết hạn VIP <?= date('d/m/Y',strtotime($post->ngay_het_han_vip)) ?></span><?php endif; ?></div></div></div></div>
  <form class="analytics-filter p-3 mb-4" method="GET"><div class="row g-2 align-items-end"><div class="col-md-4"><label class="small fw-bold form-label">Khoảng thời gian</label><select name="period" class="form-select form-select-sm"><?php foreach(['today'=>'Hôm nay','yesterday'=>'Hôm qua','7'=>'7 ngày','30'=>'30 ngày','90'=>'90 ngày','year'=>'Năm nay','custom'=>'Tùy chọn'] as $key=>$label): ?><option value="<?= $key ?>" <?= $r['period']===$key?'selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div><div class="col-md-3"><label class="small fw-bold form-label">Từ ngày</label><input type="date" name="from" value="<?= $r['from'] ?>" class="form-control form-control-sm"></div><div class="col-md-3"><label class="small fw-bold form-label">Đến ngày</label><input type="date" name="to" value="<?= $r['to'] ?>" class="form-control form-control-sm"></div><div class="col-md-2"><button class="btn btn-primary btn-sm w-100">Lọc</button></div></div></form>
  <?php $cards=[['views','View','primary'],['contacts','Contact','success'],['calls','Call','danger'],['chats','Chat','info'],['saves','Save','warning'],['shares','Share','primary'],['phones','Xem SĐT','secondary'],['zalos','Zalo','success']]; ?>
  <div class="row g-3 mb-4"><?php foreach($cards as [$key,$label,$color]): ?><div class="col-xl-3 col-6"><div class="card analytics-card p-3"><div class="analytics-label"><?= $label ?></div><div class="analytics-value text-<?= $color ?> mt-2"><?= number_format($s[$key]) ?></div></div></div><?php endforeach; ?><div class="col-6"><div class="card analytics-card p-3"><div class="analytics-label">CTR</div><div class="analytics-value mt-2"><?= number_format($s['ctr'],2) ?>%</div></div></div><div class="col-6"><div class="card analytics-card p-3"><div class="analytics-label">Conversion</div><div class="analytics-value mt-2"><?= number_format($s['conversion_rate'],2) ?>%</div></div></div></div>
  <div class="row g-3"><div class="col-12"><div class="card analytics-card p-3"><h6 class="fw-bold">Lượt xem theo ngày</h6><div class="analytics-chart"><canvas id="analyticsDailyChart"></canvas></div></div></div><div class="col-lg-6"><div class="card analytics-card p-3"><h6 class="fw-bold">Lượt xem theo tháng</h6><div class="analytics-chart"><canvas id="analyticsMonthlyChart"></canvas></div></div></div><div class="col-lg-6"><div class="card analytics-card p-3"><h6 class="fw-bold">Hành động</h6><div class="analytics-chart"><canvas id="analyticsActionsChart"></canvas></div></div></div><div class="col-lg-6"><div class="card analytics-card p-3"><h6 class="fw-bold">Nguồn truy cập</h6><div class="analytics-chart"><canvas id="analyticsSourcesChart"></canvas></div></div></div></div>
</main></div></div>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.7/dist/chart.umd.min.js"></script><script>window.AnalyticsDashboardData=<?= json_encode(['daily'=>$a['daily'],'monthly'=>$a['monthly'],'sources'=>$a['sources'],'summary'=>$s],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;</script><script src="<?= URL_ROOT ?>/public/js/analytics-dashboard.js?v=<?= filemtime(APP_ROOT . '/public/js/analytics-dashboard.js') ?>"></script>
@include('layouts.footer')
