-- Đổi tên các bảng tiếng Anh sang tiếng Việt không dấu.
-- Chạy MỘT lần trên database đang dùng tên cũ (ví dụ Railway), cùng lúc deploy code mới.
-- RENAME TABLE là nguyên tử: lỗi một bảng thì không bảng nào bị đổi. Khóa ngoại và index giữ nguyên.

RENAME TABLE
  `activity_logs` TO `nhat_ky_hoat_dong`,
  `admin_logs` TO `nhat_ky_quan_tri`,
  `backup_histories` TO `lich_su_sao_luu`,
  `categories` TO `nhom_danh_muc`,
  `chat_conversations` TO `hoi_thoai`,
  `chat_messages` TO `tin_nhan`,
  `contact_attachments` TO `tep_dinh_kem_lien_he`,
  `contacts` TO `lien_he`,
  `directions` TO `huong_nha`,
  `districts` TO `quan_huyen`,
  `error_logs` TO `nhat_ky_loi`,
  `facilities` TO `tien_ich`,
  `follows` TO `theo_doi`,
  `legal_types` TO `loai_phap_ly`,
  `live_chat_conversations` TO `hoi_thoai_truc_tuyen`,
  `live_chat_messages` TO `tin_nhan_truc_tuyen`,
  `login_history` TO `lich_su_dang_nhap`,
  `news_comments` TO `binh_luan_tin_tuc`,
  `news_likes` TO `luot_thich_tin_tuc`,
  `notifications` TO `thong_bao_nguoi_dung`,
  `otp_codes` TO `ma_otp`,
  `permissions` TO `quyen_han`,
  `post_analytics` TO `thong_ke_bai_dang`,
  `post_up_history` TO `lich_su_up_tin`,
  `projects` TO `du_an_dau_tu`,
  `provinces` TO `tinh_thanh`,
  `reward_histories` TO `lich_su_thuong`,
  `role_permissions` TO `vai_tro_quyen_han`,
  `system_log_permissions` TO `quyen_nhat_ky_he_thong`,
  `system_logs` TO `nhat_ky_he_thong`,
  `transaction_types` TO `loai_giao_dich`,
  `up_packages` TO `goi_up_tin`,
  `user_roles` TO `vai_tro_nguoi_dung`,
  `user_tokens` TO `ma_truy_cap_nguoi_dung`,
  `wards` TO `phuong_xa`;
